steps:
# Get current timestamp for build metadata
- name: 'bash'
  script: |
    echo "$(date -u +%Y-%m-%dT%H:%M:%SZ)" > /workspace/build_date.txt

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$BUILD_ID',
    '-t', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:latest',
    '--build-arg', 'BUILD_DATE=$(cat /workspace/build_date.txt)',
    '--build-arg', 'VCS_REF=$COMMIT_SHA', 
    '--build-arg', 'VERSION=$BUILD_ID',
    '.'
  ]

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$BUILD_ID']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:latest']

# Substitutions for variables
substitutions:
  _IMAGE_NAME: 'cloudrun-carbone'

# Store images in Container Registry
images:
- 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$BUILD_ID'
- 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:latest'

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'